# Conditions d'utilisation 
Pour que **InPoDa** fonctionne correctement vérifiez que les conditions suivantes doivent être réunies :
- Installation des modules : ```Pandas```, ```Textblob```, ```Spacy```, ```Translate```, ```Languedetect```, (```Gradio```?)
- Le fichier ***"aitweets.json"*** doit être dans le même dossier que **InPoDa**

# Supression des caractères spéciaux

In [65]:
# Etat : Fonctionne parfaitement 

def SuprCaracterSpe(Chaine):  # Prend en entrée une chaine de caractères 
    ChaineNettoyee = ''
    indice = 0
    while indice < len(Chaine):
        if (Chaine[indice] == 'R') and (indice < len(Chaine)-2) and (Chaine[indice] + Chaine[indice+1] == 'RT'): # On suprime les "RT"
            indice += 3
            while (indice < len(Chaine)-1) and Chaine[indice] != ' ':
                indice+=1
            ChaineNettoyee += ' '
            indice += 1
        elif (Chaine[indice].isalnum() == True):
            ChaineNettoyee += Chaine[indice]
            indice += 1
        elif (Chaine[indice] == "\ "[:-1]) and (indice < len(Chaine)-2) and (Chaine[indice] + Chaine[indice+1] == '\n'): # On suprime les sauts de ligne
            ChaineNettoyee += ' '
            indice += 1
        elif (Chaine[indice] == '@') and (indice < len(Chaine)-2):  # On suprime les pseudonymes (donc les arobases) 
            indice += 1
            while (indice < len(Chaine)-1) and Chaine[indice] != ' ':
                indice += 1
            ChaineNettoyee += ' '
            indice += 1
        else:
            ChaineNettoyee += ' '
            indice += 1
    return ChaineNettoyee     # Renvoie la chaine de cractères sans les caractères spéciaux

# Création de la classe ***Tweet***

In [66]:
class Tweet:
    
    def __init__(self, chaine='TweetParDéfaut') :
        # 'chaine' doit être un 'str'
        self.chaine = chaine # Reconversion du Tweet en 'str'

        def Hashtags(chaine): # Entrée : Chaîne de caractères
            ListeH = []
            SousChaine = chaine.split()
            for elem in SousChaine:
                if elem.startswith('#') and len(elem)>1:
                    elem2 = ''
                    indice = 1
                    while indice < len(elem):
                        if (elem[indice] == '_') or (elem[indice].isalnum() == True):
                            elem2 += elem[indice]
                            indice += 1
                        else:
                            indice = len(elem)
                    ListeH.append(elem[0]+elem2)
            return ListeH   # Renvoie une liste contenant les # du Tweet
        
        self.Hashtags = Hashtags(chaine)

        def Arobases(chaine): # Prend en entrée un str
            ListeA = []
            SousChaine = chaine.split()
            for elem in SousChaine:
                if elem.startswith('@') and len(elem)>1:
                    elem2 = ''
                    indice = 1
                    while indice < len(elem):
                        if (elem[indice] == '_') or (elem[indice].isalnum() == True):
                            elem2 += elem[indice]
                            indice += 1
                        else:
                            indice = len(elem)
                    ListeA.append(elem[0]+elem2)
            return ListeA   # Renvoie une liste contenant les @ du Tweet 

        self.Arobases = Arobases(chaine)

        def Sentiment(Tweet): # Prend en entrée une chaîne de caractères
            from textblob import TextBlob
            blob = TextBlob(Tweet)
            polarite = blob.sentiment.polarity
            if polarite > 0:
                return 'Positif'
            elif polarite < 0:
                return 'Negatif'
            else:
                return 'Neutre' # Sortie : Chaîne de caractère ('str')
            
        self.Sentiment = Sentiment(chaine)
    
    def __repr__(self):
        return self.chaine
        

chaine = "Bon @jour Je suis la"
Tweet1 = Tweet(chaine)
Tweet2 = Tweet1
type(Tweet2)

__main__.Tweet

# Récupération des Tweets du fichier Json → Json (Zone d'aterrissage)

In [67]:
# Etat : Fonctionne parfaitement

def ZoneAterrisage(NomFichier):
    from json import loads
    with open(NomFichier, 'r') as fs, open("Zone d’atterrissage.json", 'w') as fd:
        for ligne in fs:
            dicoL = loads(ligne)
            tweet = dicoL["TweetText"]
            tweetN = SuprCaracterSpe(tweet)  # Suprime tous les caractères spéciaux, les RT et les pseudonymes
            fd.write(f'{tweetN}\n')     # On écrit le Tweet nettoyé dans "Zone d’atterrissage.json"

fichier = "aitweets.json"
ZoneAterrisage(fichier)

# Récupération des Données du fichier Json → DataFrame ('DFP')

In [82]:
# Etat : Fonctionne parfaitement

def RecupDonneesP(NomFichier):  # Prend en entier le nom du fichier à analyser
    from pandas import DataFrame
    from pandas import concat
    from json import loads
    with open(NomFichier, 'r') as fs:
        ligne = fs.readline()
        dicoL = loads(ligne)
        tweet = Tweet(dicoL["TweetText"])
        dicoL["TweetText"] = tweet
        dicoL["@"] = tweet.Arobases
        dicoL["#"] = tweet.Hashtags
        dicoL["Sentiment"] = tweet.Sentiment
        DFF = DataFrame([dicoL])   # On initialise le DatFrame qui va stocker en local les données de la base
        for ligne in fs:
            dicoL = loads(ligne)
            tweet = Tweet(dicoL["TweetText"])
            dicoL["TweetText"] = tweet
            dicoL["@"] = tweet.Arobases
            dicoL["#"] = tweet.Hashtags
            dicoL["Sentiment"] = tweet.Sentiment
            DF2 = DataFrame([dicoL])
            DFF = concat([DFF,DF2])  
    DFF.index = list(i for i in range(0,1708))               
    return DFF

fichier = "aitweets.json"
DFP = RecupDonneesP(fichier)   # DFP correspond au DataFrame principal, dont les colonnes sont 'id','TweetText', etc
DFP

,id,AuthorLocation,CreatedAt,RetweetCount,TweetLanguage,TweetText,@,#,Sentiment
0,1415291904850153474,,2021-07-14T12:47:39Z,0,en,"@____bruvteresa_ According to research, NASA c...",[@____bruvteresa_],[],Positif
1,1415291947560828933,Mysore and BERLIN,2021-07-14T12:47:49Z,2,en,RT @HDataSystems: Artificial Intelligence and ...,[@HDataSystems],"[#hdatasystems, #Artificia]",Negatif
2,1415291877897605120,,2021-07-14T12:47:33Z,246,en,RT @adgpi: Army Technology Board conducted the...,[@adgpi],[],Negatif
3,1415291886860967940,,2021-07-14T12:47:35Z,1,en,"RT @pacorjo: According to a recent survey, the...",[@pacorjo],[],Positif
4,1415291968700264450,Internet,2021-07-14T12:47:54Z,20,en,RT @HarbRimah: Making AI Sing https://t.co/FJo...,[@HarbRimah],"[#MachineLearning, #DataScience, #Python, #AI,...",Neutre
...,...,...,...,...,...,...,...,...,...
1703,1421408743770791938,"Liverpool, England",2021-07-31T09:53:47Z,1,en,RT @innomaticshyd: Top 10 Real world Artificia...,[@innomaticshyd],[],Positif
1704,1421424066305605634,,2021-07-31T10:54:40Z,0,en,Iowa State part of U.S. National Science Found...,[],"[#ArtificialIntelligence, #IIoT, #GenerativeAd...",Positif
1705,1421423882427371521,127.0.0.1,2021-07-31T10:53:57Z,17,en,RT @intellimetri: Human Assisted #ArtificialIn...,"[@intellimetri, @nerdgirlz, @forbes, @ForbesBR...","[#ArtificialIntelligence, #AI]",Neutre
1706,1421423971858149377,"Singapore, Singapore",2021-07-31T10:54:18Z,12,en,RT @IainLJBrown: Artificial Intelligence learn...,[@IainLJBrown],[#Artificia],Positif
1707,1421423964845395969,"Torremolinos, España",2021-07-31T10:54:16Z,17,en,RT @marcusborba: Artificial Intelligence May F...,"[@marcusborba, @TAMU]","[#Healthcare, #A]",Negatif

# Opérations d'Analyse
Méthode : Récupération des Tweets du **DataFrame** (pincipal) → **Analyse** → **DataFrame** (d'analyse)
Les Données d'Analyse seront liées aux données du **DataFrame** principal par leur index (le numéro de leur ligne tout simplement)

Puis pour finir : Fusion des différents **DataFrame** d'Analyse. 
Par soucis de complexité (noatmment de rapidité d'exécution) nous avons opté pour un regroupement de l'exécution des opérations d'Analyse de base (#,@,sentiments,topics) au sein d'une même fonction : ```DataFrameAnalyse()```

# Les Hashtags ('#')

In [69]:
def DicoHashtags(DF):   # Entrée : DataFrame (la colonne des tweets)
    DicoH = {}
    from pandas import DataFrame
    Taille = DF.shape  # Tuple contenant (le nombre de ligne, le nombre de colonnes)
    for i in range(Taille[0]):
        tweet = DF.iloc[i]
        ListeHashtags = tweet.Hashtags 
        for h in ListeHashtags:
            if h in DicoH:
                nombre = DicoH[h]
                nombre +=1
                DicoH[h] = nombre
            else:
                DicoH[h] = 1
    del DicoH['#']    # Il y a 33 # incomplets dans la base de données, ils sont pris en compte par la fonction, on prend donc le soin de suprimer cette clé du dico           
    return DicoH      # Renvoie un Dictionnaire contenant tous les Hashtags en clé et le nombre de fois qu'ils sont tweeté en valeur

DicoH = DicoHashtags(DFP["TweetText"])

# Les Arobases @

In [70]:
def DicoArobases(DF):   # Entrée : DataFrame (la colonne des tweets)
    DicoA = {}
    from pandas import DataFrame
    Taille = DF.shape  # Tuple contenant (le nombre de ligne, le nombre de colonnes)
    for i in range(Taille[0]):
        tweet = DF.iloc[i]
        ListeArobases = tweet.Arobases
        for h in ListeArobases:
            if h in DicoA:
                nombre = DicoA[h]
                nombre +=1
                DicoA[h] = nombre
            else:
                DicoA[h] = 1 
    del DicoA['@']               
    return DicoA      # Renvoie un Dictionnaire contenant tous les Hashtags en clé et le nombre de fois qu'ils sont tweeté en valeur

DicoA = DicoArobases(DFP["TweetText"])

# Utilisateurs

L'enjeux est ici de compléter notre base de données incomplète. En effet notre base de données comporte pour chaque tweet un champ **ID** mais aucun "Pseudo" ou "Nom d'Utilisateur".
C'est pourquoi nous allons ajouter à notre **DataFrame** principal ce nouveau champ "Utilisateurs".

La création d'Utilisateurs est essentielle au bon déroulement de certaines opérations d'Analyses, notamment pour 'Les utilisateurs mentionnés par un utilisateur spécifique'. Il est donc impératif que tous les utilisateurs mentionnés dans les tweets soient présent au sein de la base de données, donc dans le champ "**Utilisateurs**" du DataFrame **DFP**.

In [71]:
# Etat : Fonctionne parfaitement

def CreationUtilisateurs(ListeD, nb, DFP):  # Entrée : Liste Utilisateurs mentionnés ('dict_keys'), nombre ('int'), DataFrame principal (DFP)
    from random import randint
    from pandas import DataFrame
    from pandas import concat
    ListeUtilisateurs = list(ListeD)
    ListeUtilisateurs.reverse()    # On inverse la liste des utilisateurs mentionnés pour éviter qu'un utilisateur se mentitonne lui même
    for i in range(nb):
        Lettre1 = chr(randint(65, 90))   # Intervalle Unicode des lettres Majuscules de l'alphabet latin
        Lettre2 = chr(randint(97, 122))  
        Lettre3 = chr(randint(97, 122))  # Intervalle Unicode des lettres Minuscules de l'alphabet latin
        Lettre4 = chr(randint(97, 122))
        Chiffre1 = chr(randint(48, 57))  # Intervalle Unicode des chiffres 
        Utilisateur = '@' + Lettre1 + Lettre2 + Lettre3 + Lettre4 + Chiffre1  # On ajoute '@' en début de Nom d'utilisateur pour s'assurer de l'homogéité des données.
        ListeUtilisateurs.append(Utilisateur)
    DFUtilisateurs = DataFrame({"Utilisateurs": ListeUtilisateurs})
    DFP = concat([DFUtilisateurs, DFP], axis=1)
    return DFP
   
DFP = CreationUtilisateurs(DicoA.keys(), (1708-len(DicoA)), DFP)
DFP

,Utilisateurs,id,AuthorLocation,CreatedAt,RetweetCount,TweetLanguage,TweetText,@,#,Sentiment
0,@TAMU,1415291904850153474,,2021-07-14T12:47:39Z,0,en,"@____bruvteresa_ According to research, NASA c...",[@____bruvteresa_],[],Positif
1,@inte,1415291947560828933,Mysore and BERLIN,2021-07-14T12:47:49Z,2,en,RT @HDataSystems: Artificial Intelligence and ...,[@HDataSystems],"[#hdatasystems, #Artificia]",Negatif
2,@ForbesBR,1415291877897605120,,2021-07-14T12:47:33Z,246,en,RT @adgpi: Army Technology Board conducted the...,[@adgpi],[],Negatif
3,@forbes,1415291886860967940,,2021-07-14T12:47:35Z,1,en,"RT @pacorjo: According to a recent survey, the...",[@pacorjo],[],Positif
4,@nerdgirlz,1415291968700264450,Internet,2021-07-14T12:47:54Z,20,en,RT @HarbRimah: Making AI Sing https://t.co/FJo...,[@HarbRimah],"[#MachineLearning, #DataScience, #Python, #AI,...",Neutre
...,...,...,...,...,...,...,...,...,...,...
1703,@Xrcl1,1421408743770791938,"Liverpool, England",2021-07-31T09:53:47Z,1,en,RT @innomaticshyd: Top 10 Real world Artificia...,[@innomaticshyd],[],Positif
1704,@Xjeg9,1421424066305605634,,2021-07-31T10:54:40Z,0,en,Iowa State part of U.S. National Science Found...,[],"[#ArtificialIntelligence, #IIoT, #GenerativeAd...",Positif
1705,@Yvqf6,1421423882427371521,127.0.0.1,2021-07-31T10:53:57Z,17,en,RT @intellimetri: Human Assisted #ArtificialIn...,"[@intellimetri, @nerdgirlz, @forbes, @ForbesBR...","[#ArtificialIntelligence, #AI]",Neutre
1706,@Otzo5,1421423971858149377,"Singapore, Singapore",2021-07-31T10:54:18Z,12,en,RT @IainLJBrown: Artificial Intelligence learn...,[@IainLJBrown],[#Artificia],Positif
1707,@Xrkc4,1421423964845395969,"Torremolinos, España",2021-07-31T10:54:16Z,17,en,RT @marcusborba: Artificial Intelligence May F...,"[@marcusborba, @TAMU]","[#Healthcare, #A]",Negatif

# Fonctionnalitées Suplémentaires :

- Actualisation manuelle des données

In [72]:
# Etat : Fonctionne parfaitement

def Refresh():
    fichier = "aitweets.json"
    ZoneAterrisage(fichier)

Refresh()

# Les TOP-K

- Top K hashtags

In [73]:
# Etat : Fonctionne parfaitement 

def TopKH(K):
    from pandas import DataFrame
    global DicoH
    DFKH = DataFrame(DicoH.items(), columns=['#', 'Nombre de Tweets'])
    if K > 0:
        DFKH = DFKH.sort_values(by='Nombre de Tweets', ascending=False) # On tri le Dataframe selon les valeurs de la deuxième colonne 'RetweetCount' et on precise 'ascending=False' pour l'ordre décroissant
    else:
        DFKH = DFKH.sort_values(by='Nombre de Tweets', ascending=True) # Inversement on tri le DataFrame par ordre Décroissant
    return DFKH.head(abs(K))  # On passe la valeur absolue de K dans la méthode .head() pour s'assurer qu'elle affiche correctement le Top demandé
         # Sortie : DataFrame de deux colonnes contenant les Utilisateurs mentionnés et le Nombre de fois qu'ils ont été mentionné

TopKH(5)

                          #  Nombre de Tweets
11  #ArtificialIntelligence               207
5                       #AI               204
2          #MachineLearning                86
27                      #ai                52
3              #DataScience                50

- Top K Utilisateurs

In [74]:
def TopKU(K):   # Entrée : Entier ('int')
    from pandas import concat
    global DFP
    Taille = DFP["RetweetCount"].shape
    for i in range(Taille[0]):
        valeur = int(DFP["RetweetCount"].loc[i])  # On converti les 'str' de la colonne "RetweetCount" en entier pour correctement les trier
        DFP["RetweetCount"].loc[i] = valeur       
    DFKU = concat([DFP["Utilisateurs"], DFP["RetweetCount"]], axis=1)
    if K > 0:
        DFKU = DFKU.sort_values(by="RetweetCount", ascending=False) # On tri le Dataframe selon les valeurs de la deuxième colonne 'RetweetCount' et on precise 'ascending=False' pour l'ordre décroissant
    else:
        DFKU = DFKU.sort_values(by="RetweetCount", ascending=True) # Inversement on tri le DataFrame par ordre Décroissant
    return DFKU.head(abs(K))  # On passe la valeur absolue de K dans la méthode .head() pour s'assurer qu'elle affiche correctement le Top demandé
         # Sortie : DataFrame de deux colonnes contenant les Utilisateurs mentionnés et le Nombre de fois qu'ils ont été mentionné 

TopKU(5)

         Utilisateurs RetweetCount
1194           @Gbzw3        10327
1585           @Frml6         6481
1587           @Auns1         6481
735   @LuxuryOpinions         1660
1047          @SecDef         1060

- Top K utilisateurs mentionnés

In [75]:
# Etat : Fonctionne parfaitement 

def TopKA(K):  # Entrée : Entier ('int')
    from pandas import DataFrame
    global DicoA
    DFKA = DataFrame(DicoA.items(), columns=['@', 'Nombre de Mentions'])
    if K > 0:
        DFKA = DFKA.sort_values(by='Nombre de Mentions', ascending=False) # On tri le Dataframe selon les valeurs de la deuxième colonne 'Nombre' et on precise 'ascending=False' pour l'ordre décroissant
    else:
        DFKA = DFKA.sort_values(by='Nombre de Mentions', ascending=True) # Inversement on tri le DataFrame par ordre Décroissant  
    return DFKA.head(abs(K))  # On passe la valeur absolue de K dans la méthode .head() pour s'assurer qu'elle affiche correctement le Top demandé
         # Sortie : DataFrame de deux colonnes contenant les Utilisateurs mentionnés et le Nombre de fois qu'ils ont été mentionné 

TopKA(5)

                  @  Nombre de Mentions
26     @IainLJBrown                 112
55   @Paula_Piccard                  49
18     @nigewillson                  24
679  @JoshuaBarbeau                  17
977       @sankrant                  17

# Le Nombre de publication par Utilisateur/Hashtag

- Le nombre de publications par utilisateur

In [76]:
def NbPostUtilisateur(Utilisateur) : # Entrée : 'str' (Le Nom de l'utilisateur)
    global DFP
    Taille = DFP.shape
    for i in range(Taille[0]):
        if DFP["Utilisateurs"].loc[i] == Utilisateur:
            return (Utilisateur, DFP["RetweetCount"].loc[i])  
    return (Utilisateur, 0)   # Sortie : 'tuple' (Utilisateur, nombre de Publications)
NbPostUtilisateur("@adgpi")

('@adgpi', 27)

- Le nombre de publications par hashtag

In [77]:
def NbPostHashtags(hashtag): # Entrée : 'str' 
    global DicoH
    if hashtag in DicoH:
        return (hashtag, DicoH[hashtag])
    else:
        return (hashtag, 0) # Sortie : 'tuple' (#, nombre de publications dans lequel il est mentionné)
    
NbPostHashtags('#AI')

('#AI', 204)

# Les dernières analyses demandées

- L’ensemble de tweets d’un utilisateur spécifique

In [78]:
def TweetsUtilisateur(Utilisateur): # Entrée : Nom de l'Utilisateur ('str')
    from pandas import DataFrame
    if Utilisateur[0] != "@":
        Utilisateur = "@" + Utilisateur
    ExpressionR = 'RT ' + Utilisateur
    ListeTweets = []
    global DFP
    Taille = DFP["TweetText"].shape
    for indice in range(Taille[0]):
        Tweet = DFP["TweetText"].loc[indice]
        if (ExpressionR in Tweet.chaine) and (Tweet.chaine[len(ExpressionR)+2:] not in ListeTweets):
            ListeTweets.append(Tweet.chaine[len(ExpressionR)+2:])
        elif (DFP["Utilisateurs"].loc[indice] == Utilisateur):
            ListeTweets.append(Tweet)
    if ListeTweets == []:
        return DataFrame([{"Tweets postés par : " + Utilisateur:"Erreur : Aucun Tweet posté"}])
    else:
        return DataFrame({"Tweets postés par : " + Utilisateur:ListeTweets}) 
     # Sortie : DataFrame contenant les à chaque ligne un tweet de l'utilisateur (Tweet brut) et attention l'index des Tweets de DFTU ne correspondent pas à leur index dans DFP

TweetsUtilisateur("@Gizchina")

                       Tweets postés par : @Gizchina
0  OPPO releases its first 6G white paper. A syst...
1  RT @sfchronicle: “Intellectually, I know it’s ...

- L’ensemble de tweets mentionnant un utilisateur spécifique

In [79]:
def TweetsMentionUtilisateur(Utilisateur): # Entrée : Nom de l'Utilisateur ('str' commençant par un @)
    from pandas import DataFrame
    global DFP
    Taille = DFP.shape
    ListeIndiceTweets = []
    for i in range(Taille[0]):
        ListeA = DFP["@"].loc[i]
        if Utilisateur in ListeA:
            ListeIndiceTweets.append(i)
    DFTMU = DataFrame(DFP["TweetText"].iloc[ListeIndiceTweets])
    DFTMU = DFTMU.rename(columns={"TweetText":"Tweets mentionnant : " + Utilisateur})  # On renomme la colonne pour plus de clarté 
    return DFTMU     # Sortie : DataFrame contenant à chaque ligne les Tweets mentionnant l'Utilisateur, l'index de chaque ligne correpond à celui du Tweet brut stocké dans DFP 

TweetsMentionUtilisateur("@intratio")

                        Tweets mentionnant : @intratio
75   RT @intratio: $MDVL https://t.co/rso4WTkGcW Me...
400  RT @intratio: https://t.co/GGI5g1FRD3 Kinnate ...
843  RT @intratio: $CUE https://t.co/N3KHKWvbdp Cue...

- Les utilisateurs mentionnant un hashtag spécifique

In [80]:
def UtilisateurMentionHashtag(Hashtag): # Entrée : Un Hastag (donc un 'str' débutant par "#")
    from pandas import DataFrame
    global DFP
    Taille = DFP.shape
    ListeIndiceTweets = []
    for i in range(Taille[0]):
        ListeH = DFP["#"].loc[i]
        if Hashtag in ListeH:
            ListeIndiceTweets.append(i)
    if ListeIndiceTweets == []:
        return DataFrame([{"Utilisateurs":"Erreur : Votre Hashtag n'existe pas"}])
    else:
        return DataFrame(DFP["Utilisateurs"].iloc[ListeIndiceTweets]) 
              # Sortie : Un DataFrame contenant à chaque ligne un Utilisateur qui à mentionner le Hashtag dans son tweet, l'index correspond à celui de l'Utilisateur dans DFA 

UtilisateurMentionHashtag('#AI')

         Utilisateurs
4          @nerdgirlz
8        @arXiv_Daily
10    @DecisionsSmart
42       @frontiersin
58       @TACHOUHONER
...               ...
1679           @Sfvx6
1681           @Gxbc9
1684           @Xgfr8
1699           @Mhzv5
1705           @Yvqf6

[200 rows x 1 columns]

- Les utilisateurs mentionnés par un utilisateur spécifique

In [81]:
def UtilisateurMentionUtilsateur(Utilisateur):  # Entrée : Nom de l'Utilisateur ('str' commençant par un @)
    from pandas import DataFrame
    global DFP
    Taille = DFP.shape
    for i in range(Taille[0]):
        if DFP["Utilisateurs"].loc[i] == Utilisateur:
            return DataFrame({Utilisateur + " a mentionné :":DFP["@"].loc[i]})   # Sortie : Un DataFrame contenant à chaque ligne un utilisateur mentionné par l'Utilisateur 
    return DataFrame([{"Utilisateurs":"Erreur : Votre Utilisateur n'existe pas"}]) # Sortie : Un DataFrame contenant un avertissement sur l'inexistence de l'Utilisateur 

UtilisateurMentionUtilsateur("@xoce_q")

  @xoce_q a mentionné :
0      @codewithibrahim

# Interface Graphique de Inpoda

- Gradio

# Ressources suplémentaires
Des ressources suplémentaire sont disponible sur le Github dont le lien est ci dessous. Vous y trouverez notamment un diagramme détaillant le fonctionnement de **InPoDa** ainsi que le détail de la répartition des taches. 

Github : https://github.com/LugolBis/Projet-IN304